openapi: 3.0.0
info:
  title: Hello World
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /hello-world:
    post:
      summary: "Performs hello world"
      operationId: "helloWorld"
      requestBody:
        required: true
        x-name: data
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Name to be printed"

      responses:
        200:
          description: Hello response
        405:
          description: "Invalid input"
        default:
          description: Unexpected error